Feature/19 refactor nav
szkola-reacta/team-d-app pull request #23
Opened 2020-11-16 13:24 UTC by WronskiN

Refactored component to enable user to reuse component in random places of the project. Use your own styles if necessary.

2020-11-17 20:01 UTC, LukasMod approved these changes
It would be good to have some deafult css for ul without background color and width/hight - in case <NavList> component without {showMenu}. I would recommand for example to add className={'navListDefault ${showNav}'} with some of navList styles e.g .navListDefault { display: flex; flex-direction: column; justify-content: center; align-items: center; list-style: none; } and define some of navList style there. My point is to separate the character of the menu in the header from the menu itself. What do you guys think?

2020-11-17 20:01 UTC, LukasMod commented on src/components/Nav/NavList.js
> +    <ul className={showMenu}>
deafult css for `ul` d for example to add   `className={'navListDefault ${showMenu}'}`

2020-11-17 20:55 UTC, WronskiN commented on src/components/Nav/NavList.js
> +    <ul className={showMenu}>
Very good point LukasMod. I will implement these changes later on. Thanks.

2020-11-18 13:14 UTC, weronikaolejniczak requested changes
I believe that you should also pass **a class name for NavLink** as a prop to the component **NavList**, pass it on to **NavItem** and in NavItem declare a _className_ for **NavLink** using this prop, so that _navLink_ (in NavItem) class you pass on for styling doesn't take precedence over whatever styling we do for NavList comp.
I hope it's understandable, if not I prepared some code :D

2020-11-18 13:14 UTC, weronikaolejniczak commented on src/components/Nav/NavList.js
> +    <ul className={showMenu}>
I agree. Default styles could include _list-style: none;_ to get rid of the bullet points.

2020-11-18 13:14 UTC, weronikaolejniczak commented on src/components/Nav/NavList.js
> +    <ul className={showMenu}>
And instead of naming it **showMenu**, I'd call it **navListClass**. It makes the purpose of it clearer, at least for me. **showMenu** sounds more like a boolean.

2020-11-18 18:54 UTC, WronskiN commented
I have made changes as suggested. Please check and confirm.

2020-11-18 20:00 UTC, weronikaolejniczak requested changes

2020-11-18 20:00 UTC, weronikaolejniczak commented on src/components/Nav/NavList.js
> +function NavList({ navListClass, defaultClass }) {
Here we also have to pass in **navLinkClass** and then later instead of "_navLinkDefault_" use this value. Otherwise, even if we style **NavList**, _navLinkDefault_ class style will take precedence.

2020-11-18 20:00 UTC, weronikaolejniczak commented on src/components/Nav/NavList.js
> +          navLinkClass="navLinkDefault"
So here we pass in _navLinkClass_. We can say if it's **undefined**, then the class will be _navLinkDefault_.

2020-11-18 20:36 UTC, weronikaolejniczak approved these changes

2020-11-18 20:37 UTC, merged